---
apiVersion: v1
kind: Pod
metadata:
  labels:
    andela-build-agent: true
spec:
  containers:
  - name: kubectl
    image: roffe/kubectl:v1.13.2
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    env:
    - name: KUBECONFIG
      value: /kubeconfig/config
    volumeMounts:
    - name: kubeconfig
      mountPath: /kubeconfig
      readOnly: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"
  volumes:
  - name: kubeconfig
    secret:
      secretName: kubeconfig